### ISSUE TITLE
In AREditor can't select all types of methods from robot service (e.g. move_relative_joints/stop)

### ISSUE THREAD

**Issue by NelaMm** [robofit/arcor2_kinali#40]

**Comment by ZdenekM** [comment]
- Method ```move_relative_joints``` was missing action metadata. Fixed in https://github.com/robofit/arcor2_kinali/commit/5d96cf8d02480b9b5d81242c31cfde16b4ce989f.
- ```stop``` is not an action by purpose. It does not make much sense I think to have it as action. All actions (so far) are blocking. So if you e.g. run move, you anyway has to wait until it finishes. In the Editor/main script it is not possible to call ```stop``` in the middle of movement. There is going to be a Stop button in the editor - I created an issue for it (https://github.com/robofit/arcor2_editor/issues/114).
